out/production/Online sop/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

out/production/Online sop/objects/Reporting_period__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Reporting period</label>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testFillProductStore.cls
/**
 * Created by a2.buyko on 26.10.18.
 */

@IsTest
private class testFillProductStore {
    @IsTest
    static void testBehavior() {
        Reporting_period__c reportDate = new Reporting_period__c();
        reportDate.Name = 'Reporting_week';
        reportDate.onlineStore__Reporting_Date__c = Date.today().addDays(7);
        insert  reportDate;
        Product__c product = new Product__c();
        product.Name = 'product';
        product.onlineStore__Number_of_purchase__c = 1;
        product.onlineStore__Date_of_receipt__c = Date.today() + 1;
        Database.SaveResult result = Database.insert(product);
        System.debug(result);
        System.debug([SELECT id FROM Store__c].size());
        System.assert([SELECT id FROM Store__c].size() == 1);
        System.assert(result.isSuccess());
    }
}