out/production/Online sop/objects/Raw_materials__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_receipt__c</fullName>
        <label>Date of receipt</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Made_in__c</fullName>
        <label>Made in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quality__c</fullName>
        <label>Quality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Raw materials</relationshipLabel>
        <relationshipName>Raw_materials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Raw material</label>
    <nameField>
        <label>Raw materials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Raw materials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FileUploadWebService.cls
/**
 * Created by a2.buyko on 9.1.19.
 */

global class FileUploadWebService {
    webservice static void postFileData(List<String> listRaw, String storeId) {
        List<Raw_materials__c> newRaws= convertingDataToRawMaterials(listRaw, storeId);
        AddRawMaterialsBatchClass rawBatch = new AddRawMaterialsBatchClass(newRaws);
        Database.executeBatch(rawBatch);
    }

    webservice static List<Raw_materials__c> getRawMaterials(String storeId) {
        return [SELECT Id, Name, Quality__c, Amount__c, Made_in__c, Date_of_receipt__c FROM Raw_materials__c WHERE Store__c =: storeId];
    }

    static Map<String, Schema.SObjectField> mapFieldAndFileTitle(List<String> labels){
        Map<String, Schema.SObjectField> mapLabelsAndField = new Map<String, Schema.SObjectField>();
        Map<String, Schema.SObjectField> fieldMap = Raw_materials__c.SObjectType.getDescribe().fields.getMap();
        System.debug(labels);
        for (Schema.SObjectField field : fieldMap.values()){

            if (labels.contains(field.getDescribe().getLabel()) || labels.contains(field.getDescribe().getName())) {
                mapLabelsAndField.put(labels.contains(field.getDescribe().getLabel())
                        ? field.getDescribe().getLabel()
                        : field.getDescribe().getName(), field);
            }
        }
        return mapLabelsAndField;
    }

    static List<Raw_materials__c> convertingDataToRawMaterials(List<String> listRaw, String storeId){
        List<String> labels = listRaw.get(0).remove('\n').split(',');
        Map<String, Schema.SObjectField> mapLabels = mapFieldAndFileTitle(labels);
        listRaw.remove(0);
        List<Raw_materials__c> newRaws = new List<Raw_materials__c>();
        for (String stringRaw : listRaw){
            Raw_materials__c rawMaterials = new Raw_materials__c();
            List<String> listFieldsData = stringRaw.remove('\n').split(',');
            for (Integer i = 0; i < listFieldsData.size(); i++){
                rawMaterials.put(mapLabels.get(labels.get(i)), DynamicConvert.convert(mapLabels.get(labels.get(i)), listFieldsData[i]));
                rawMaterials.put('Store__c', storeId);
            }
            newRaws.add(rawMaterials);
        }
        return newRaws;
    }
}